# Config for Jenkins credentials
# Do not add credential values directly to this file.
# Credentials pulled from SSM
# See: https://github.com/jenkinsci/configuration-as-code-plugin/blob/master/docs/features/secrets.adoc 
credentials:
  system:
    domainCredentials:
    - credentials:
      - basicSSHUserPrivateKey:
          id: "jenkins-build-node"
          privateKeySource:
            directEntry:
              privateKey: ${/jenkins/config/buildnode/privatekey}
          scope: GLOBAL
          username: ${/jenkins/config/buildnode/username}
      - usernamePassword:
          id: "jenkins-service-user"
          password: ${/jenkins/config/serviceuser/token}
          scope: GLOBAL
          username: ${/jenkins/config/serviceuser/username}
      - basicSSHUserPrivateKey:
          description: "lybuilder with ssh key credentails"
          id: "lybuilder-ssh-key"
          privateKeySource:
            directEntry:
              privateKey: ${/jenkins/config/buildnode/privatekey}
          scope: GLOBAL
          username: ${/jenkins/config/buildnode/username}
      - usernamePassword:
          id: "github"
          password: ${/jenkins/config/github/token}
          scope: GLOBAL
          username: ${/jenkins/config/github/username}
      - usernamePassword:
          id: "build-failure-rca-kb"
          password: ${/jenkins/config/bfa/password}
          scope: GLOBAL
          username: ${/jenkins/config/bfa/username}
      - usernamePassword:
          description: "Upstream Sync"
          id: "705110e5-1be6-4bf3-b3d7-3b720426c0d4"
          password: ${/jenkins/config/upstream-sync/token}
          scope: GLOBAL
          username: ${/jenkins/config/upstream-sync/username}
      - usernamePassword:
          id: "tiaf-testing"
          password: ${/jenkins/config/tiaf/token}
          scope: GLOBAL
          username: ${/jenkins/config/tiaf/username}
