# Config for Jenkins global environment variables
jenkins:
  globalNodeProperties:
  - envVars:
      env:
      - key: "AP_LOGS_S3_BUCKET"
        value: "ap-logs"
      - key: "BRANCH_DEFAULT"
        value: "development"
      - key: "BUILD_SNAPSHOT_BRANCHES"
        value: "stabilization/2111RTE"
      - key: "CPACK_UPLOAD_URL"
        value: "s3://spectra-prism-staging-us-west-2"
      - key: "DEFAULT_ES_HOSTS"
        value: ${/jenkins/config/mars/url}
      - key: "DEFAULT_REPOSITORY_NAME"
        value: "Lumberyard"
      - key: "GITHUB_USER"
        value: "github"
      - key: "INSTALLER_BUCKET"
        value: "spectra-prism-staging-us-west-2"
      - key: "INSTALLER_DOWNLOAD_URL"
        value: "https://dkb1uj4hs9ikv.cloudfront.net"
      - key: "INSTALLER_S3_BUCKET"
        value: "s3://o3de-prism-prod-us-west-2"
      - key: "IS_UPLOAD_AP_LOGS"
        value: "True"
      - key: "IS_UPLOAD_TEST_ARTIFACTS"
        value: "True"
      - key: "JENKINS_ARTIFACTS_S3_BUCKET"
        value: "ly-o3de-fork-jenkins-artifacts"
      - key: "LFS_URL"
        value: "d3df09qsjufr6g.cloudfront.net/api/v1"
      - key: "LY_PACKAGE_SERVER_URLS"
        value: ${/jenkins/config/3p-package-urls}
      - key: "MARS_NOTIFICATIONS"
        value: ${/jenkins/config/mars/notification}
      - key: "MARS_REPO"
        value: "https://github.com/aws-lumberyard/o3de-mars.git"
      - key: "O3DE_METRICS_S3_BUCKET"
        value: "s3://o3de-metrics/csv/"
      - key: "POST_AR_BUILD_SNS_TOPIC"
        value: "arn:aws:sns:us-west-2:288697475520:post-ar-build"
      - key: "S3SIS_SOURCE"
        value: "s3://ly-s3sis-source/configure"
      - key: "SERVICE_USER"
        value: "jenkins-service-user"
      - key: "SNAP_RETENTION"
        value: "1"
      - key: "SNS_TOPIC"
        value: "arn:aws:sns:us-west-2:288697475520:pull_request_build_complete"
      - key: "SNS_TOPIC_GITHUB_ISSUE"
        value: "arn:aws:sns:us-west-2:288697475520:create-github-issue"
      - key: "TEST_IMPACT_S3_BUCKET"
        value: "o3de-tiaf"
      - key: "TEST_IMPACT_WIN_BINARY"
        value: "c:\\ly\\3rdParty\\packages\\OpenCppCoverage\\Binary\\windows-x64\\OpenCppCoverage.exe"
      - key: "TEST_SCREENSHOT_BUCKET"
        value: "ly-spectra-jenkins-pipelines-test-screenshots"
      - key: "VALIDATOR_NOTIFICATIONS"
        value: ${/jenkins/config/validation/notification}
