# Config for Jenkins global environment variables
jenkins:
  globalNodeProperties:
  - envVars:
      env:
      - key: "AP_LOGS_S3_BUCKET"
        value: "ap-logs"
      - key: "BRANCH_DEFAULT"
        value: "development"
      - key: "CPACK_UPLOAD_URL"
        value: "s3://spectra-prism-staging-us-west-2"
      - key: "DEFAULT_REPOSITORY_NAME"
        value: "o3de" 
      - key: "ES_HOSTS"
        value: "\"https://prod.mars.agscollab.com:443\""
      - key: "GITHUB_USER"
        value: "github"
      - key: "INSTALLER_BUCKET"
        value: "spectra-prism-staging-us-west-2"
      - key: "INSTALLER_DOWNLOAD_URL"
        value: "https://dkb1uj4hs9ikv.cloudfront.net"
      - key: "INSTALLER_S3_BUCKET"
        value: "s3://o3de-prism-prod-us-west-2"
      - key: "IS_UPLOAD_AP_LOGS"
        value: "True"
      - key: "IS_UPLOAD_TEST_ARTIFACTS"
        value: "True"
      - key: "JENKINS_ARTIFACTS_S3_BUCKET"
        value: "ly-o3de-fork-jenkins-sandbox-artifacts"
      - key: "LY_PACKAGE_SERVER_URLS"
        value: "s3://ly-prod-3p-packages;s3://ly-dev-3p-packages;s3://ly-prod-provo-3p-packages;s3://ly-prod-xenia-3p-packages;s3://ly-prod-salem-3p-packages;s3://ly-prod-jasper-3p-packages;s3://ly-dev-provo-3p-packages;s3://ly-dev-xenia-3p-packages;s3://ly-dev-salem-3p-packages;s3://ly-dev-jasper-3p-packages;"
      - key: "MARS_REPO"
        value: "https://github.com/aws-lumberyard/o3de-mars.git"
      - key: "POST_AR_BUILD_SNS_TOPIC"
        value: ${/jenkins/config/post-ar-build-topic}
      - key: "SERVICE_USER"
        value: "jenkins-service-user"
      - key: "SNAP_RETENTION"
        value: "1"
      - key: "TEST_IMPACT_S3_BUCKET"
        value: "o3de-tiaf"
      - key: "TEST_IMPACT_WIN_BINARY"
        value: "c:\\ly\\3rdParty\\packages\\OpenCppCoverage\\Binary\\windows-x64\\OpenCppCoverage.exe"
      - key: "TEST_SCREENSHOT_BUCKET"
        value: "ly-spectra-jenkins-pipelines-test-screenshots"
      - key: "VALIDATOR_NOTIFICATIONS"
        value: "ly-validators@amazon.com,ly-spectra-ops@amazon.com,ly-infra@amazon.com"
