jenkins:
  numExecutors: 6  # Jenkins pipeline runs some pre/post-build pipeline tasks on the controller. Increased from default (2) to prevent long queues.
  securityRealm:
    saml:
      advancedConfiguration:
        forceAuthn: false
        nameIdPolicyFormat: "urn:oasis:names:tc:SAML:2.0:nameid-format:transient"
        spEntityId: ${/jenkins/config/url}
      binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
      displayNameAttributeName: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
      emailAttributeName: "EMAIL"
      groupsAttributeName: "POSIX_GROUPS"
      idpMetadataConfiguration:
        period: 0
        url: ${/jenkins/config/idp-url}
      maximumAuthenticationLifetime: 86400
      usernameCaseConversion: "lowercase"
  authorizationStrategy:
    projectMatrix:
      permissions:
      - "Overall/Administer:${ADMIN_ROLE}"  # User/group assigned as admin. For additional permissions see matrix_authorization.template
  remotingSecurity:
    enabled: true
unclassified:
  location:
    url: ${/jenkins/config/url}
    adminAddress: "${/jenkins/config/email}"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleOnOver
  email-ext:
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
    - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    mailAccount:
      smtpHost: "${/jenkins/config/smtp-host}"
      smtpPassword: "${/jenkins/config/smtp-password}"
      smtpUsername: "${/jenkins/config/smtp-username}"
      useTls: true
security:
  scriptApproval:
    approvedSignatures:
    - "field hudson.plugins.git.GitSCM GIT_BRANCH"
    - "field hudson.plugins.git.GitSCM GIT_COMMIT"
    - "method hudson.model.Cause$UserIdCause getUserId"
    - "method hudson.model.Run getCause java.lang.Class"
    - "method java.net.URL getHost"
    - "method java.net.URL getPort"
    - "method java.net.URL getProtocol"
    - "new java.net.URL java.lang.String java.lang.String int java.lang.String"
    - "method org.jenkinsci.plugins.workflow.steps.FlowInterruptedException getCauses"
    - "method org.jenkinsci.plugins.workflow.support.steps.build.RunWrapper getRawBuild"
    - "new java.net.URL java.lang.String java.lang.String int java.lang.String"
    - "staticMethod jenkins.model.Jenkins getInstance"
