jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  labelString: "controller"
  markupFormatter:
    rawHtml:
      disableSyntaxHighlighting: false
  noUsageStatistics: true
  numExecutors: 6  # Jenkins pipeline runs some pre/post-build pipeline tasks on the controller. Increased from default (2) to prevent long queues.
  securityRealm:
    saml:
      advancedConfiguration:
        forceAuthn: false
        nameIdPolicyFormat: "urn:oasis:names:tc:SAML:2.0:nameid-format:transient"
        spEntityId: ${/jenkins/config/url}
      binding: "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
      displayNameAttributeName: "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name"
      emailAttributeName: "EMAIL"
      groupsAttributeName: "POSIX_GROUPS"
      idpMetadataConfiguration:
        period: 0
        url: ${/jenkins/config/idp-url}
      maximumAuthenticationLifetime: 86400
      usernameCaseConversion: "lowercase"
  remotingSecurity:
    enabled: true
unclassified:
  location:
    url: ${/jenkins/config/url}
    adminAddress: "${/jenkins/config/admin-address}"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleOnOver
  mailer:
    authentication:
      password: ${/jenkins/config/mail/password}
      username: ${/jenkins/config/mail/username}
    charset: "UTF-8"
    smtpHost: "email-smtp.us-west-2.amazonaws.com"
    useTls: true
security:
  scriptApproval:
    approvedSignatures:
    - "field hudson.plugins.git.GitSCM GIT_COMMIT"
    - "field hudson.plugins.git.GitSCMBackwardCompatibility source"
    - "field hudson.plugins.git.UserRemoteConfig refspec"
    - "field java.lang.String value"
    - "method groovy.lang.Closure leftShift groovy.lang.Closure"
    - "method groovy.lang.GroovyObject getProperty java.lang.String"
    - "method groovy.lang.GroovyObject invokeMethod java.lang.String java.lang.Object"
    - "method hudson.model.Actionable getActions"
    - "method hudson.model.PersistenceRoot getRootDir"
    - "method java.lang.Throwable getStackTrace"
    - "method java.net.URL getHost"
    - "method java.net.URL getPort"
    - "method java.net.URL getProtocol"
    - "method jenkins.model.Jenkins getItemByFullName java.lang.String"
    - "method jenkins.plugins.git.AbstractGitSCMSource$SCMRevisionImpl getHash"
    - "method jenkins.scm.api.SCMRevisionAction getRevision"
    - "method org.jenkinsci.plugins.workflow.steps.FlowInterruptedException getCauses"
    - "method org.jenkinsci.plugins.workflow.support.steps.build.RunWrapper getRawBuild"
    - "new groovy.lang.Tuple2 java.lang.Object java.lang.Object"
    - "new java.io.File java.lang.String"
    - "new java.net.URL java.lang.String java.lang.String int java.lang.String"
    - "staticMethod jenkins.model.Jenkins getInstance"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods drop java.lang.Object[]\
      \ int"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods getAt java.lang.Object\
      \ java.lang.String"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods putAt java.lang.Object\
      \ java.lang.String java.lang.Object"
    - "staticMethod org.codehaus.groovy.runtime.DefaultGroovyMethods size java.util.regex.Matcher"
